# =============================================================================
# ASM Bootstrap Variables
# Generated by OpenTofu on ${timestamp()}
# Source infrastructure: region=${region}, environment=${environment}
#
# Usage:
#   1. Create a new project (or use this one) with modules/asm/
#   2. Run: tofu apply -var-file=asm-bootstrap.auto.tfvars
#   3. Set asm_version below to a version available in your OTC region
#      (check OTC console → ASM → Create Mesh for available versions)
#
# IMPORTANT: installation_nodes must not be empty. If the list below is
# empty, run: tofu apply  (second apply after nodes are Ready) to regenerate.
# =============================================================================

# ---- CCE Cluster ----

cce_cluster_id   = "${cluster_id}"
cce_cluster_name = "${cluster_name}"

# ---- ASM Mesh identity ----
# Set this to the mesh name you want (must be 4–64 chars, lowercase, hyphens ok)

mesh_name = "${cluster_name}"

# ---- ASM version ----
# Check available versions in OTC console → ASM → Create Mesh
# Minimum for mTLS: 1.15   Minimum for apm-otel tracing: 1.18
# EDIT THIS VALUE before applying:

asm_version = "1.18.7-r5"

# ---- Node IDs for ASM control-plane installation ----
# For HA (3-node) clusters: supply all 3 node IDs
# For single-node clusters: supply just the 1 node ID

cce_installation_node_ids = ${jsonencode(installation_nodes)}

# ---- Network ----

vpc_id    = "${vpc_id}"
subnet_id = "${subnet_id}"

# ---- Namespaces to pre-configure for sidecar injection ----
# Add your application namespace names here, or label them manually later:
#   kubectl label namespace <ns> istio-injection=enabled

asm_injection_namespaces = []

# ---- Cluster metadata ----

region            = "${region}"
environment       = "${environment}"
high_availability = ${high_availability}

# ---- ELB (for workloads Ingress annotations) ----
# Annotate your Kubernetes Ingress resources with:
#   kubernetes.io/elb.id: "<elb_id>"

elb_id = "${elb_id}"
node_sg_id = "${node_sg_id}"
