# ---------------------------------------------------------------------------
# istio.env — Istio deployment configuration
# Generated by OpenTofu at apply time. Do not edit manually.
#
# Sourced automatically by 2-asm scripts.
# Override individual values on the command line or by setting env vars
# before running the scripts.
# ---------------------------------------------------------------------------

# Whether the CCE cluster was deployed in HA mode.
# install uses this to set istiod replica count (1 for non-HA, 3 for HA).
# Override with --ha or --no-ha on the command line.
ISTIO_HA=${high_availability}

# Default Istio version to install.
# Override with --version <version> on the command line.
ISTIO_VERSION="${istio_version}"

# Path to the generated kubeconfig.
# Override by setting KUBECONFIG in your environment before running.
ISTIO_KUBECONFIG="${kubeconfig_path}"
