apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-redir
  namespace: local-tools
  annotations:
    kubernetes.io/ingress.class: cce
    kubernetes.io/elb.id: {{ .Values.elbId | quote }}
    kubernetes.io/elb.class: {{ .Values.elbClass | quote }}
    kubernetes.io/elb.port: "80"
spec:
  ingressClassName: cce
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-redir
            port:
              number: 80
