#!/bin/sh
#
set -euf ; (set -o pipefail 2>/dev/null) && set -o pipefail

die() {
  echo "$@" 1>&2
  exit 1
}
envconfig() {
  local v="$1" d="$2"
  eval [ -z '"${'"$1"':-}"' ] && eval "$v=\"\$2\""
  :
}
envconfig SOCKSPORT 1080
envconfig RUSER ""
vars_dir=.

while [ $# -gt 0 ]
do
  case "$1" in
  -e) vars_dir="$2" ; shift 2 ;;
  --vars-dir=*) vars_dir=${1#--vars-dir=} ; shift ;;
  --socks=*) SOCKSPORT="${1#--socks=}" ;;
  --socksport=*) SOCKSPORT="${1#--socksport=}" ;;
  -s) SOCKSPORT="${2}" ; shift ;;
  -s?*) SOCKSPORT="${1#-s}" ;;
  --ruser=*) RUSER="${1#--ruser=}" ;;
  -u) RUSER="${2}" ; shift ;;
  -u?*) RUSER="${1#-u}" ;;
  *) break ;;
  esac
  shift
done

exports_dir=$(readlink -f "$(dirname "$0")/../1-infra/exports/")
[ ! -f "$exports_dir/kube.env" ] \
  && die "Missing exports/kube.env:  Make sure 1-infra was run succesfully"

set -a
. "$exports_dir/kube.env" || die "Invalid configuration"
set +a


mydir=$(readlink -f "$(dirname "$0")")
oIFS="$IFS" ; IFS="
"
for _f in $(find "$vars_dir" -mindepth 1 -maxdepth 1 '(' -name '*.env' -o -name '*.env.sh' ')' )
do
  IFS="$oIFS"
  set -a
  [ -f "$_f" ] && . "$_f"
  set +a
done
IFS="$oIFS"
unset _f oIFS

case "$EXT_BASTION_HOST" in
*@*) [ -n "$RUSER" ] && echo "EXT_BASTION_HOST already has a remote user name, RUSER ignored" 1>&2 ;;
*) [ -n "$RUSER" ] && EXT_BASTION_HOST="${RUSER}@${EXT_BASTION_HOST}"
esac

if [ x"${1:-}" = x"-k" ] ; then
  found=$(ps ax | awk '$5 == "ssh" && /-D  *1080  *-N  */ && /'"$EXT_BASTION_HOST"'/ { print $1 }')
  if [ -n "$found" ] ; then
    kill "$found"
    rc=$?
    echo "Killing proxy ($found)..." 1>&2
  else
    echo "Proxy Process not found" 1>&2
    rc=1
  fi
  exit $rc
fi

echo "Using $EXT_BASTION_HOST:$SOCKSPORT" 1>&2

if ! nc -z localhost $SOCKSPORT ; then
  echo "Launching proxy" 1>&2
  if ! ssh -o batchmode=yes $EXT_BASTION_HOST true ; then
    echo "Unable to log in to $EXT_BASTION_HOST" 1>&2
    if (echo "$EXT_BASTION_HOST" | grep -q '@') ; then
      host="$(echo "$EXT_BASTION_HOST" | cut -d@ -f2-)"
    else
      host="$EXT_BASTION_HOST"
    fi
    echo -n "Try to remove $host from known hosts?:? [y/N]: "
    read -r CONFIRM
    case "$CONFIRM" in
    [yY][eE][sS]|[yY])
      ssh-keygen -R "$host"
      ;;
    *) echo "Skipping..." ;;
    esac
    echo -n "Try to connect interactively to $EXT_BASTION_HOST?:? [y/N]: "
    read -r CONFIRM
    case "$CONFIRM" in
    [yY][eE][sS]|[yY]) ssh "$EXT_BASTION_HOST" || exit 1 ;;
    *) echo "Giving up..." 1>&2 ; exit 1 ;;
    esac
  fi
  ssh -D $SOCKSPORT -N $EXT_BASTION_HOST &
  sshpid="$!"
  sleep 3
  echo "ssh/socks proxy running ($sshpid)" 1>&2
fi

export HTTPS_PROXY=socks5://localhost:$SOCKSPORT
export KUBECONFIG=$(readlink -f "$(dirname "$0")/../1-infra/exports/kubeconfig")

if [ $# -eq 0 ] ; then
  kubectl version
  rc=$?
  cat <<-EOF
	Usage: $0 [options] cmd

	Options:
	-u : Remote user
	-s : socks port
	-k : Kill proxy process
	EOF
  exit $rc
fi

"$@"

